### PR TITLE
Fix a bug where the `onerror` callback could try to be called when it had already been destroyed

### PR DESCRIPTION
**Pull request by hamchapman**
If there was an error establishing a WebSocket connection at an `await` point
and after the point at which the `onerror` etc callbacks had been set but before
the `WsStream` had been constructed then the `onerror` callback would try to be
called but it would have already been destroyed because of the future being
cancelled.

This could happen if, for example, the initial attempt to connect to a WebSocket
server timed out and we never observed an event at this `await` point:

```rust
let mut evts = pharos.observe( Self::OPEN_CLOSE.into() ).await
```

To fix this we introduce a guard that is only active across the `await` points
in the `WsMeta::connect` function. It is temporarily responsible for
unregistering the callbacks in the case that the future is cancelled before the
`WsStream` is constructed.

The error that you'd otherwise run into would present itself like this in the
logs:

```
ERROR: Error: closure invoked recursively or destroyed already
    at imports.wbg.__wbindgen_throw (http://localhost:61367/package/web/ditto.es6.js:1:70261)
    at wasm_bindgen::throw_str::hf6afd94675c6db0f (http://localhost:61367/package/web/ditto.wasm:wasm-function[119306]:0x3327743)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h2944e7516b507b14 (http://localhost:61367/package/web/ditto.wasm:wasm-function[49343]:0x2c601d8)
    at __wbg_adapter_36 (http://localhost:61367/package/web/ditto.es6.js:1:12851)
    at WebSocket.real (http://localhost:61367/package/web/ditto.es6.js:1:11649)
```

### CODE REVIEW

**Review by danielhenrymantilla — APPROVED** [review]

**Comment by najamelan** [comment]
Apologies for the delay. I wasn't paying attention to github and they seem to have stopped sending emails... I will look into this today.

**Comment by najamelan** [comment]
Im going to make a test to reproduce this. Im thinking probably the guard should close the websocket itself as well to assure proper cleanup.

**Comment by najamelan** [comment]
Also we may want to log something when this happens.

**Comment by najamelan** [comment]
Thanks for reporting this and submitting a solution. I managed to reproduce the issue. Unfortunately the errors you show above were the only indication of what was happening. Thus I added a log warning indicating the future was dropped and called close on the websocket. The final output looks like:

Screenshot from 2023-01-29 18-15-27

I will fix the pipeline, merge this in and release a new version.

**Comment by najamelan** [comment]
A patch release 0.7.4 is out with this fix. Thanks to @danielhenrymantilla also for the review of this PR.

**Comment by danielhenrymantilla** [comment]
Thanks @najamelan!

**Pull request merged**
